version: "3"

services:
  nestjs-app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - postgres
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  pgadmin:
    image: dpage/pgadmin4:6.20
    networks:
      - postgres
    ports:
      - ${PGADMIN_PORT_SERVER}:${PGADMIN_PORT_CLIENT}
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

networks:
  postgres:
    driver: bridge