version: "3"

services:
  nestjs-app:
    build:
      dockerfile: Dockerfile
      context: .
      target: install-dependencies
    command: yarn start:inspect
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    depends_on:
      - postgres
      - pgadmin
      - redis
    networks:
      - postgres
  postgres:
    image: postgres:15.1
    restart:
      always
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  pgadmin:
    image: dpage/pgadmin4:6.20
    restart:
      always
    networks:
      - postgres
    ports:
      - ${PGADMIN_PORT_SERVER}:${PGADMIN_PORT_CLIENT}
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    restart:
      always
    networks:
      - postgres
    volumes:
      - /data/redis:/data/redis
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

networks:
  postgres:
    driver: bridge
