export const SALT_LENGTH = "SALT_LENGTH";
export const ACCESS_TOKEN_PUBLIC_KEY = "ACCESS_TOKEN_PUBLIC_KEY";
export const ACCESS_TOKEN_PRIVATE_KEY = "ACCESS_TOKEN_PRIVATE_KEY";
export const REFRESH_TOKEN_PUBLIC_KEY = "REFRESH_TOKEN_PUBLIC_KEY";
export const REFRESH_TOKEN_PRIVATE_KEY = "REFRESH_TOKEN_PRIVATE_KEY";
export const ACCESS_TOKEN_TTL = "ACCESS_TOKEN_TTL";
export const REFRESH_TOKEN_TTL = "REFRESH_TOKEN_TTL";
export const REFRESH_TOKEN_COOKIE_TTL = "REFRESH_TOKEN_COOKIE_TTL";
